<?php

declare(strict_types=1);

namespace BreathTakinglyBinary\npcs\entities;

use pocketmine\entity\Human;
use pocketmine\entity\Location;
use pocketmine\entity\Skin;

class NPCHuman extends Human {

    private string $NPCID;

    public function __construct(string $npcid, string $name, Location $location, Skin $skin) {
        $this->NPCID = $npcid;
        $this->setNameTagAlwaysVisible(true);
        $this->setNameTag($name);
        $this->setImmobile(true);
        parent::__construct($location, $skin);
    }

    protected function tryChangeMovement() : void{

    }

    public function sendData($player, ?array $data = null) : void{
        parent::sendData($player, $data); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getNPCID() : string{
        return $this->NPCID;
    }
}
